// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: proto/RAG.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_proto_RAG_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RAG_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_RAG_proto_rawDescGZIP(), []int{0}
}

func (x *FileUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// Response message confirming upload and processing
type FileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       bool                   `protobuf:"varint,1,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadResponse) Reset() {
	*x = FileUploadResponse{}
	mi := &file_proto_RAG_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResponse) ProtoMessage() {}

func (x *FileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RAG_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResponse.ProtoReflect.Descriptor instead.
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_RAG_proto_rawDescGZIP(), []int{1}
}

func (x *FileUploadResponse) GetMessage() bool {
	if x != nil {
		return x.Message
	}
	return false
}

func (x *FileUploadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_RAG_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RAG_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_RAG_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_RAG_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RAG_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_RAG_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_proto_RAG_proto protoreflect.FileDescriptor

const file_proto_RAG_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/RAG.proto\x12\n" +
	"ragservice\"I\n" +
	"\x11FileUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"D\n" +
	"\x12FileUploadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\bR\amessage\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"$\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"'\n" +
	"\rQueryResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer2\xa2\x01\n" +
	"\n" +
	"RAGService\x12K\n" +
	"\n" +
	"UploadFile\x12\x1d.ragservice.FileUploadRequest\x1a\x1e.ragservice.FileUploadResponse\x12G\n" +
	"\x10QueryWithContext\x12\x18.ragservice.QueryRequest\x1a\x19.ragservice.QueryResponseB\x04Z\x02./b\x06proto3"

var (
	file_proto_RAG_proto_rawDescOnce sync.Once
	file_proto_RAG_proto_rawDescData []byte
)

func file_proto_RAG_proto_rawDescGZIP() []byte {
	file_proto_RAG_proto_rawDescOnce.Do(func() {
		file_proto_RAG_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_RAG_proto_rawDesc), len(file_proto_RAG_proto_rawDesc)))
	})
	return file_proto_RAG_proto_rawDescData
}

var file_proto_RAG_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_RAG_proto_goTypes = []any{
	(*FileUploadRequest)(nil),  // 0: ragservice.FileUploadRequest
	(*FileUploadResponse)(nil), // 1: ragservice.FileUploadResponse
	(*QueryRequest)(nil),       // 2: ragservice.QueryRequest
	(*QueryResponse)(nil),      // 3: ragservice.QueryResponse
}
var file_proto_RAG_proto_depIdxs = []int32{
	0, // 0: ragservice.RAGService.UploadFile:input_type -> ragservice.FileUploadRequest
	2, // 1: ragservice.RAGService.QueryWithContext:input_type -> ragservice.QueryRequest
	1, // 2: ragservice.RAGService.UploadFile:output_type -> ragservice.FileUploadResponse
	3, // 3: ragservice.RAGService.QueryWithContext:output_type -> ragservice.QueryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_RAG_proto_init() }
func file_proto_RAG_proto_init() {
	if File_proto_RAG_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_RAG_proto_rawDesc), len(file_proto_RAG_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_RAG_proto_goTypes,
		DependencyIndexes: file_proto_RAG_proto_depIdxs,
		MessageInfos:      file_proto_RAG_proto_msgTypes,
	}.Build()
	File_proto_RAG_proto = out.File
	file_proto_RAG_proto_goTypes = nil
	file_proto_RAG_proto_depIdxs = nil
}
